version = 3.5.8
runner.dialect = "Scala213Source3"

align.preset = most
align.multiline = false
assumeStandardLibraryStripMargin = true
docstrings.style = keep
optIn.annotationNewlines = true
optIn.breakChainOnFirstMethodDot = true
indentOperator.excludeRegex = "^$"
lineEndings = preserve
maxColumn = 160
# newlines.beforeMultiline = unfold
newlines.neverInResultType = true
newlines.source=keep
rewrite.rules = [Imports, PreferCurlyFors, RedundantBraces, RedundantParens, SortModifiers]
rewrite.redundantBraces.generalExpressions = false
rewrite.redundantBraces.methodBodies = false
rewrite.redundantBraces.parensForOneLineApply = true
rewrite.redundantBraces.stringInterpolation = true
trailingCommas = preserve
rewrite.imports.sort = scalastyle
rewrite.imports.groups =  [["(?!javax?\\.).*", "(?!scala\\.).*"], ["javax?\\..*", "scala\\..*"]]
